# Generated by Django 3.0.3 on 2020-07-30 16:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_auto_20200730_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2020, 7, 30, 16, 36, 45, 485172, tzinfo=utc))),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='Users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Profile')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tweet.Tweet')),
            ],
        ),
    ]
