# Generated by Django 3.0.3 on 2020-07-31 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_auto_20200731_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 12, 42, 42, 656421, tzinfo=utc)),
        ),
    ]
