# Generated by Django 3.0.3 on 2020-08-01 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0015_auto_20200802_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 18, 39, 32, 801575, tzinfo=utc)),
        ),
    ]
