# Generated by Django 3.0.3 on 2020-07-31 12:50

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20200731_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/None/no_image.jpg', upload_to=Users.models.upload_to),
        ),
    ]
