# Generated by Django 3.0.3 on 2020-08-01 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20200802_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower',
        ),
        migrations.AlterField(
            model_name='follow',
            name='follow_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 18, 39, 32, 793805, tzinfo=utc)),
        ),
    ]
