# Generated by Django 3.0.3 on 2020-08-02 12:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20200802_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follow_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 12, 17, 2, 515184, tzinfo=utc)),
        ),
    ]
